### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bltierney** [EtWnn/CryptoPrice#35]
Your library looks to be exactly what I need! But when I try to install it, I get this error:

I get this error on install:
>pip3 install python-CryptoPrice
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
python-CryptoPrice depends on cbpro@ git+https://github.com/teleprint-me/coinbasepro-python.git@2.1.28

I dont need  coinbase support (only binance and kucoin), so is there an easy way to remove that dependency?

**Comment by EtWnn** [comment]
Thank you for writing this issue! This went unoticed on my side

The coinbasepro-python package was deleted and no official client library exists as of now.
As such, the coinbase support was removed from this package.

Removal PR: #36 
Merged on main: #38
